version: "3"
services:
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      mongoURI: mongodb://localhost:27017
      baseUrl: http://localhost:5000
    depends_on: 
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
