swagger: "2.0"
info:
  title: URL shortner
  description: This is my url shoetner API Documentation
  version: 1.0.0
  servers:
    -url: http://localhost:5000
    description: This is my local Server

#Return Tasks From get request
paths:
  #Post request
  /api/url/shorten:
    post:
      summary: Adds a new task
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/components/schemas/URL"
      responses:
        "201":
          description: OK
        "422":
          description: the post body is empty


#Schemas
components:
  schemas:
    URL:
      type: object
      required:
        - longUrl
      properties:
        longUrl:
          type: string
